# 📝 Quiz de Conceptos — Capítulo 7: Cambios de Base

---

Este quiz evalúa tu comprensión de los conceptos centrales. Intenta **responder cada
pregunta antes de ver la solución**. Cada pregunta tiene su propia celda de respuesta.

| Pregunta | Tema |
|:---:|:---|
| 1 | Encontrar coordenadas en una base no estándar |
| 2 | Columnas de la matriz $P$ |
| 3 | Representación de una transformación en nueva base |
| 4 | Propiedades de matrices similares |
| 5 | Verdadero/Falso: toda matriz invertible como cambio de base |

> 💬 *Úsalo como autoevaluación después de estudiar la teoría.*

## ❓ Pregunta 1

Sea $\mathcal{B} = \{\mathbf{b}_1, \mathbf{b}_2\}$ con $\mathbf{b}_1 = (1,1)^\top$ y $\mathbf{b}_2 = (-1,1)^\top$.

Encuentra las coordenadas del vector $\mathbf{v} = (3, 1)^\top$ en la base $\mathcal{B}$.

Es decir, encuentra $c_1, c_2$ tales que $c_1 \mathbf{b}_1 + c_2 \mathbf{b}_2 = \mathbf{v}$.

```{toggle} 💡 Pista
Construye la matriz $P = [\mathbf{b}_1 | \mathbf{b}_2]$ y resuelve $P\mathbf{c} = \mathbf{v}$, es decir,
calcula $\mathbf{c} = P^{-1}\mathbf{v}$.
```

In [1]:
import numpy as np

# Pregunta 1: Coordenadas en la base B
b1 = np.array([1., 1.])
b2 = np.array([-1., 1.])
v = np.array([3., 1.])

P = np.column_stack([b1, b2])
print("Matriz P:")
print(P)

# Método 1: resolver sistema lineal
c = np.linalg.solve(P, v)
print(f"\n✅ Solución: [v]_B = {c}")
print(f"   c1 = {c[0]}, c2 = {c[1]}")

# Verificación
v_check = c[0]*b1 + c[1]*b2
print(f"\nVerificación: {c[0]}·{b1} + {c[1]}·{b2} = {v_check}")
print(f"¿Igual a v? {np.allclose(v_check, v)} ✓")

# Interpretación
print("\n📌 Respuesta: las coordenadas de (3,1) en la base B son:")
print(f"   [v]_B = (c1, c2) = ({c[0]:.3f}, {c[1]:.3f})")
print("   Esto significa: v = 2·b1 + (-1)·b2")

Matriz P:
[[ 1. -1.]
 [ 1.  1.]]

✅ Solución: [v]_B = [ 2. -1.]
   c1 = 2.0, c2 = -1.0

Verificación: 2.0·[1. 1.] + -1.0·[-1.  1.] = [3. 1.]
¿Igual a v? True ✓

📌 Respuesta: las coordenadas de (3,1) en la base B son:
   [v]_B = (c1, c2) = (2.000, -1.000)
   Esto significa: v = 2·b1 + (-1)·b2


## ❓ Pregunta 2

Sea $\mathcal{B} = \{\mathbf{b}_1, \mathbf{b}_2, \mathbf{b}_3\}$ una base de $\mathbb{R}^3$.

**¿Qué son las columnas de la matriz $P$ que convierte de base $\mathcal{B}$ a la base estándar?**

Elige la respuesta correcta:

a) Las filas son los vectores de $\mathcal{B}$ expresados en coordenadas estándar.

b) Las **columnas** son los vectores de $\mathcal{B}$ expresados en coordenadas estándar.

c) Las columnas son los vectores estándar expresados en coordenadas $\mathcal{B}$.

d) Las columnas son los autovectores de $\mathcal{B}$.

```{toggle} ✅ Respuesta
La respuesta correcta es **(b)**.

$P = [\mathbf{b}_1 \mid \mathbf{b}_2 \mid \mathbf{b}_3]$ donde cada $\mathbf{b}_i$ se escribe en coordenadas estándar.

Multiplicar $P \cdot [\mathbf{v}]_\mathcal{B}$ convierte de coordenadas $\mathcal{B}$ a coordenadas estándar,
porque $P[\mathbf{v}]_\mathcal{B} = c_1\mathbf{b}_1 + c_2\mathbf{b}_2 + c_3\mathbf{b}_3 = \mathbf{v}$.
```

In [2]:
import numpy as np

# Verificación de la Pregunta 2
# Sea B = {(1,2,0), (0,1,3), (1,0,1)}
b1 = np.array([1., 2., 0.])
b2 = np.array([0., 1., 3.])
b3 = np.array([1., 0., 1.])

# P se forma con b1, b2, b3 como COLUMNAS
P = np.column_stack([b1, b2, b3])
print("Columnas de P (= vectores de la base B):")
print(f"  Columna 1 (b1): {P[:,0]}")
print(f"  Columna 2 (b2): {P[:,1]}")
print(f"  Columna 3 (b3): {P[:,2]}")

# Demostración: P convierte de coordenadas B a estándar
v_B = np.array([2., 1., -1.])  # coordenadas en B
v = P @ v_B
print(f"\nSi [v]_B = {v_B}, entonces:")
print(f"v = P @ [v]_B = {v}")
print(f"Verificación manual: 2*b1 + 1*b2 + (-1)*b3 = {2*b1 + 1*b2 + (-1)*b3}")

print("\n✅ Las COLUMNAS de P son los vectores de la base B en coordenadas estándar.")

Columnas de P (= vectores de la base B):
  Columna 1 (b1): [1. 2. 0.]
  Columna 2 (b2): [0. 1. 3.]
  Columna 3 (b3): [1. 0. 1.]

Si [v]_B = [ 2.  1. -1.], entonces:
v = P @ [v]_B = [1. 5. 2.]
Verificación manual: 2*b1 + 1*b2 + (-1)*b3 = [1. 5. 2.]

✅ Las COLUMNAS de P son los vectores de la base B en coordenadas estándar.


## ❓ Pregunta 3

Sea $A$ la matriz de una transformación lineal $T: \mathbb{R}^2 \to \mathbb{R}^2$ en la base estándar.
Sea $P$ la matriz de cambio de base a la base $\mathcal{B}$.

**¿Cuál es la matriz de $T$ en la base $\mathcal{B}$?**

a) $PAP^{-1}$

b) $P^{-1}AP$

c) $PA$

d) $AP^{-1}$

```{toggle} ✅ Respuesta y demostración
La respuesta es **(b)**: $A_\mathcal{B} = P^{-1}AP$.

**Razonamiento:** Para aplicar $T$ a $[\mathbf{v}]_\mathcal{B}$:
1. Convierte a estándar: $\mathbf{v} = P[\mathbf{v}]_\mathcal{B}$
2. Aplica $T$: $A\mathbf{v} = AP[\mathbf{v}]_\mathcal{B}$
3. Convierte de vuelta: $P^{-1}AP[\mathbf{v}]_\mathcal{B}$
Por tanto $A_\mathcal{B} = P^{-1}AP$.
```

In [3]:
import numpy as np

# Pregunta 3: Transformación en nueva base
# T = rotación 90° en R², A = [[0,-1],[1,0]]
A = np.array([[0., -1.],
              [1.,  0.]])

# Nueva base B = {(1,1)/√2, (-1,1)/√2}
b1 = np.array([1., 1.]) / np.sqrt(2)
b2 = np.array([-1., 1.]) / np.sqrt(2)
P = np.column_stack([b1, b2])

# Calcular A_B con la fórmula correcta: P^{-1} A P
A_B = np.linalg.inv(P) @ A @ P
print("Transformación T (rotación 90°) en base estándar:")
print(A)

print("\nMatriz de cambio de base P:")
print(np.round(P, 4))

print("\nA_B = P^{-1}AP:")
print(np.round(A_B, 6))

# Comparar con PAP^{-1} (respuesta incorrecta)
wrong = P @ A @ np.linalg.inv(P)
print("\nPAP^{-1} (respuesta incorrecta a):")
print(np.round(wrong, 6))

print("\n✅ La representación correcta de T en base B es A_B = P^{-1}AP")

Transformación T (rotación 90°) en base estándar:
[[ 0. -1.]
 [ 1.  0.]]

Matriz de cambio de base P:
[[ 0.7071 -0.7071]
 [ 0.7071  0.7071]]

A_B = P^{-1}AP:
[[ 0. -1.]
 [ 1. -0.]]

PAP^{-1} (respuesta incorrecta a):
[[-0. -1.]
 [ 1.  0.]]

✅ La representación correcta de T en base B es A_B = P^{-1}AP


## ❓ Pregunta 4

Si dos matrices $A$ y $B$ son similares (existe $P$ invertible tal que $B = P^{-1}AP$),
¿cuáles de las siguientes propiedades comparten?

Marca todas las correctas:

- [ ] a) $\det(A) = \det(B)$
- [ ] b) $\text{tr}(A) = \text{tr}(B)$
- [ ] c) Los mismos autovalores
- [ ] d) Las mismas entradas (elementos iguales)
- [ ] e) El mismo rango
- [ ] f) El mismo polinomio característico

```{toggle} ✅ Respuesta
Las respuestas correctas son: **(a), (b), (c), (e), (f)**.

La opción (d) es **falsa** — matrices similares pueden tener entradas completamente diferentes.
La similitud preserva propiedades *invariantes de equivalencia*, no las entradas individuales.
```

In [4]:
import numpy as np

# Pregunta 4: verificar propiedades de matrices similares
A = np.array([[5., 2.],
              [1., 4.]])

P = np.array([[2., 1.],
              [1., 1.]])

B = np.linalg.inv(P) @ A @ P

print("Matrices similares:")
print(f"A =\n{A}")
print(f"B = P^{{-1}}AP =\n{np.round(B, 6)}")
print("\nNota: las entradas son DISTINTAS (desmentimos opción d)")

print("\n" + "="*45)
print("Propiedades compartidas (a, b, c, e, f):")
print(f"  det(A) = {np.linalg.det(A):.4f}")
print(f"  det(B) = {np.linalg.det(B):.4f}")
print(f"  tr(A)  = {np.trace(A):.4f}")
print(f"  tr(B)  = {np.trace(B):.4f}")
lA = np.sort(np.linalg.eigvals(A))
lB = np.sort(np.linalg.eigvals(B))
print(f"  λ(A) = {np.round(lA, 4)}")
print(f"  λ(B) = {np.round(lB, 4)}")
print(f"  Mismos autovalores: {np.allclose(lA, lB)} ✓")

print("\n✅ Propiedades iguales: det, traza, autovalores, rango, polinomio caract.")
print("❌ Propiedad NO compartida: las entradas individuales")

Matrices similares:
A =
[[5. 2.]
 [1. 4.]]
B = P^{-1}AP =
[[6. 2.]
 [0. 3.]]

Nota: las entradas son DISTINTAS (desmentimos opción d)

Propiedades compartidas (a, b, c, e, f):
  det(A) = 18.0000
  det(B) = 18.0000
  tr(A)  = 9.0000
  tr(B)  = 9.0000
  λ(A) = [3. 6.]
  λ(B) = [3. 6.]
  Mismos autovalores: True ✓

✅ Propiedades iguales: det, traza, autovalores, rango, polinomio caract.
❌ Propiedad NO compartida: las entradas individuales


## ❓ Pregunta 5: Verdadero o Falso

Indica si cada afirmación es **Verdadera (V)** o **Falsa (F)**:

1. **Toda matriz invertible puede ser una matriz de cambio de base.**

2. **Si $P$ es la matriz de cambio de base de $\mathcal{B}$ a estándar, entonces $P^{-1}$ lleva de estándar a $\mathcal{B}$.**

3. **La matriz de cambio de base entre dos bases ortogonales siempre tiene determinante $\pm 1$.**

4. **Dos matrices similares siempre tienen las mismas entradas en la diagonal.**

5. **Si $A$ es diagonal, es similar a sí misma con $P = I$.**

```{toggle} ✅ Respuestas
1. **Verdadero.** Cualquier matriz invertible tiene columnas l.i., que pueden ser una base.
2. **Verdadero.** $[\mathbf{v}]_\mathcal{B} = P^{-1}\mathbf{v}$ — exactamente.
3. **Verdadero.** Las matrices ortogonales tienen $|\det| = 1$.
4. **Falso.** Las diagonales pueden ser completamente distintas (aunque la traza y los autovalores se preservan).
5. **Verdadero.** $I^{-1}AI = A$ — trivialmente.
```

In [5]:
import numpy as np

print("Verificación de las afirmaciones Verdadero/Falso:\n")

# 1. Toda matriz invertible puede ser cambio de base
P_test = np.array([[2., 3.], [1., 4.]])
print(f"1. Verdadero: det(P) = {np.linalg.det(P_test):.2f} ≠ 0 → columnas son base válida")

# 2. P^{-1} lleva de estándar a B
b1 = np.array([2., 1.]); b2 = np.array([1., 3.])
P = np.column_stack([b1, b2])
v = np.array([5., 4.])
v_B = np.linalg.inv(P) @ v  # de estándar a B
v_rec = P @ v_B              # de B a estándar
print(f"2. Verdadero: P^{{-1}} v = {np.round(v_B,4)}, P @ P^{{-1}} v = {np.round(v_rec,4)} = v ✓")

# 3. Base ortogonal → det = ±1
theta = np.radians(37)
P_ort = np.array([[np.cos(theta), -np.sin(theta)],
                  [np.sin(theta),  np.cos(theta)]])
print(f"3. Verdadero: det(P_ortogonal) = {np.linalg.det(P_ort):.6f} ≈ ±1")

# 4. Matrices similares, distintas diagonales
A = np.array([[3., 1.], [0., 2.]])
P2 = np.array([[1., 1.], [1., 2.]])
B = np.linalg.inv(P2) @ A @ P2
print(f"4. Falso: diagonal(A) = {np.diag(A)}, diagonal(B) = {np.round(np.diag(B),4)} — distintas")

# 5. A similar a sí misma con P=I
A_diag = np.diag([3., 5.])
print(f"5. Verdadero: I^{{-1}} @ A_diag @ I = A_diag: {np.allclose(np.eye(2)@A_diag@np.eye(2), A_diag)}")

print("\n✅ Quiz completado!")

Verificación de las afirmaciones Verdadero/Falso:

1. Verdadero: det(P) = 5.00 ≠ 0 → columnas son base válida
2. Verdadero: P^{-1} v = [2.2 0.6], P @ P^{-1} v = [5. 4.] = v ✓
3. Verdadero: det(P_ortogonal) = 1.000000 ≈ ±1
4. Falso: diagonal(A) = [3. 2.], diagonal(B) = [ 6. -1.] — distintas
5. Verdadero: I^{-1} @ A_diag @ I = A_diag: True

✅ Quiz completado!
